# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Prady's XYZ"
email: prady@tuta.io
name: "Prady Neog"
description: "A personal blog site containing technical information."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pradyneo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: /android-chrome-192x192.png
twitter_username: pradyneo
github_username:  pradyneo
github: [metadata]
repository: "pradyneo/pradyneo.github.io"
permalink: none
breadcrumbs: true

# Build settings
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
include: ["_pages"]

timezone: America/New_York

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives

defaults:
# _posts
- scope:
    path: ""
    type: posts
  values:
    layout: single
    read_time: true
    #related: true
    share: true
    permalink: /:categories/:title/

#_pages
- scope:
    path: ""
    type: pages
  values:
    layout: single

#analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-139225033-3"
    anonymize_ip: false # default

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
